
#
#    PRINT "Load users schema"
#    mongo < users.js &>>$LOG
#    STAT $?



- name: Copy MongoDB YUM Repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update mongodb Listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start and Enable mongodb
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download App content & Extract it
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project-v1/{{COMPONENT}}/archive/refs/heads/main.zip
    dest: "/tmp"
    remote_src: yes

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
    loop:
      - catalogue
      - user

