- name: Create ALl Roboshop parameters
  hosts: localhost
  tasks:
    - name: Create or update key/value pair in AWS SSM parameter store
      community.aws.ssm_paramater:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: "us-east-1"
      loop:
        - {name: "param.dev.catalogue.MONGO", value: "true"}
        - { name: "param.dev.user.MONGO", value: "true" }
