-
  name: Copy Prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml


- name: Restart prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for port 9090 to become open on the host
  ansible.builtin.wait_for:
    port: 9090
    host: 0.0.0.0
    delay: 5
    timeout: 5
