route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
    - name: "email"
      email_configs:
        - to: venugopal.challa369@gmail.com      # you@example.com
          from: venugopal.challa369@gmail.com  # alertmanager@example.com
          smarthost: "email-smtp.us-east-1.amazonaws.com:587"
          auth_username: "{{SES_ USR}}"
          auth_password: "{{SES_ PSW}}"
          require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
